version: '3'
services:
    stickerbot:
        build:
            context: .
            args:
                TOKEN: ${TOKEN}
        network_mode: 'host'
        restart: unless-stopped
        container_name: 'stickerbot'
        volumes:
            - ~/storage/stickerlogs:/usr/src/app/logs
