version: '3'
services:
    stickerbot:
        build:
            context: .
            args:
                TOKEN: ${TOKEN}
        container_name: 'stickerbot'
        volumes:
            - ./../stickerlogs:/usr/src/app/logs
            - ./../stickerdb:/usr/src/app/db
